/**
 * FILENAME:  Bag.java
 * WHO:       Diana Eastman 
 * WHEN:      May 17, 2013
 * WHAT:      Represents the pool of letters (a "bag") where from players get new letters.
 */

import javafoundations.*;
import java.util.*;

public class Bag {
  //Instance variables
  private static LinkedList<Tile> tileBagList;
  private static LinkedQueue<Tile> tileBagQueue;
        
  /**
   * Constructor. Adds the standard set of tiles (98 in total) to the "Bag" of available
   * tiles. Tiles added to the bag by iterating through tiles array in Tile class (the 
   * 26 tiles in the alphabet) in the outer loop and looping within the inner loop the 
   * number of times the tile tile appears in the bag (e.g., there are 9 As, but only
   * 1 Z in the standard Scrabble bag). The tiles are then randomly shuffled and added to
   * a linked queue.
   */
  public Bag() 
  {                   
    tileBagList = new LinkedList<Tile>();
    tileBagQueue = new LinkedQueue<Tile>();
    for (char i : Tile.letters){ 
      for (int j = 0; j < Tile.getAmountOfTilesInBag(i); j++){
        tileBagList.add(new Tile(i));
      }
    }
    shuffleBag(); //Shuffle the tiles 
    enqueueShuffledBag(); //Enqueue the shuffled tiles into a LinkedQueue
  }
  
  /**
   * Generates a random number for each Tile's index in the Bag (Linked List) and swaps
   * the Tile to the index of the random number.
   */
  private void shuffleBag() 
  {
    int n = tileBagList.size();  
    Random random = new Random();
    random.nextInt();
                
    for (int i = 0; i < n; i++) {
      int change = i + random.nextInt(n - i);
      swap(tileBagList, i, change);
    }
  }

  /**
   * Helper method for <code>shuffleBag</code>. Swaps the Tile from i to its new index
   * @param a Linked List of Tile Objects
   * @param the Tile's original index in the LL
   * @param the Tile's destination index in the LL, generated by random
   */
  private void swap(LinkedList<Tile> bag, int i, int change) 
  {
    Tile helper = bag.get(i);
    bag.set(i, bag.get(change));          
    bag.set(change, helper);
  }
  
  /**
   * Adds each Tile in the Bag LL to a Linked Queue of Tile objects. This allows
   * easy access to the next Tile in the Bag.
   */
  private void enqueueShuffledBag() 
  {
    for (int i = 0; i<tileBagList.size(); i++)
      tileBagQueue.enqueue(tileBagList.get(i));
  }
  
  /**
   * Gets the next tile from the queue ("Bag") if not queue is not empty.
   * @return Tile the next tile (order generated by adding in a random order)
   */
  public static Tile getNext()
  {
    if(tileBagQueue.isEmpty())
      return null;           
    return(tileBagQueue.dequeue());
  }
  
  /**
   * Returns true when the Bag of tiles is empty.
   * @return <code>true</code> if there are no items left in the Bag and false otherwise
   */
  public static boolean isEmpty()
  {
   return tileBagQueue.isEmpty(); 
  }
  
  /**
   * String representation of the Bag of Tiles 
   * @return String
   */
  public String toString()
  {
   String s = "";
   s+="There are " + tileBagList.size() + " tiles in the bag. \n";
   for (int i = 0; i<tileBagList.size(); i++)
      s+=tileBagList.get(i);
   return s; 
  }
  
  // Testing method
  public static void main (String args[]){
   Bag test = new Bag();
   System.out.println(test);
   System.out.println(test.getNext());
  }
}